name: Generate 3D Profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: thiernodaoudaly

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A .
          git commit -m "chore: update 3D profile" || exit 0
          git push